#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : perl-Business-ISSN
Version  : 1.003
Release  : 2
URL      : https://cpan.metacpan.org/authors/id/B/BD/BDFOY/Business-ISSN-1.003.tar.gz
Source0  : https://cpan.metacpan.org/authors/id/B/BD/BDFOY/Business-ISSN-1.003.tar.gz
Summary  : 'Perl extension for International Standard Serial Numbers'
Group    : Development/Tools
License  : Artistic-2.0
Requires: perl-Business-ISSN-man

%description
=pod
=encoding utf8
=for HTML <a href="https://travis-ci.org/briandfoy/business-issn"><img src="https://travis-ci.org/briandfoy/business-issn.svg?branch=master" /></a>

%package man
Summary: man components for the perl-Business-ISSN package.
Group: Default

%description man
man components for the perl-Business-ISSN package.


%prep
%setup -q -n Business-ISSN-1.003

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
if test -f Makefile.PL; then
%{__perl} Makefile.PL
make  %{?_smp_mflags}
else
%{__perl} Build.PL
./Build
fi

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make TEST_VERBOSE=1 test

%install
rm -rf %{buildroot}
if test -f Makefile.PL; then
make pure_install PERL_INSTALL_ROOT=%{buildroot}
else
./Build install --installdirs=site --destdir=%{buildroot}
fi
find %{buildroot} -type f -name .packlist -exec rm -f {} ';'
find %{buildroot} -depth -type d -exec rmdir {} 2>/dev/null ';'
find %{buildroot} -type f -name '*.bs' -empty -exec rm -f {} ';'
%{_fixperms} %{buildroot}/*

%files
%defattr(-,root,root,-)
/usr/lib/perl5/site_perl/5.26.1/Business/ISSN.pm

%files man
%defattr(-,root,root,-)
/usr/share/man/man3/Business::ISSN.3
